import { definePlugin, defineTool, inputSchema } from "@openvesper/plugin-sdk";
import { strategyEMAcross, strategyRSI, strategyMACD, strategyBollingerBreakout, compareAllStrategies, runCustomStrategy } from "./tools";

export default definePlugin({
  name: "@openvesper/plugin-strategies", version: "1.0.0", author: "OpenVesper",
  description: "Strategy backtesting — EMA, RSI, MACD, Bollinger", license: "MIT",
  tools: [
    defineTool({ name: "strategy_ema_cross", description: "EMA crossover backtest", inputSchema: inputSchema({ symbol: { type: "string", description: "Symbol" }, interval: { type: "string", description: "1h, 4h, 1d" }, fast: { type: "number", description: "Fast period" }, slow: { type: "number", description: "Slow period" }, days: { type: "number", description: "Backtest days" } }, ["symbol"]), handler: async (i) => strategyEMAcross(i.symbol as string, (i.interval as string) || "1h", (i.fast as number) || 50, (i.slow as number) || 200, (i.days as number) || 30), category: "quant" }),
    defineTool({ name: "strategy_rsi", description: "RSI mean reversion backtest", inputSchema: inputSchema({ symbol: { type: "string", description: "Symbol" }, interval: { type: "string", description: "TF" }, oversold: { type: "number", description: "RSI buy" }, overbought: { type: "number", description: "RSI sell" }, days: { type: "number", description: "Days" } }, ["symbol"]), handler: async (i) => strategyRSI(i.symbol as string, (i.interval as string) || "1h", (i.oversold as number) || 30, (i.overbought as number) || 70, (i.days as number) || 30), category: "quant" }),
    defineTool({ name: "strategy_macd", description: "MACD momentum backtest", inputSchema: inputSchema({ symbol: { type: "string", description: "Symbol" }, interval: { type: "string", description: "TF" }, days: { type: "number", description: "Days" } }, ["symbol"]), handler: async (i) => strategyMACD(i.symbol as string, (i.interval as string) || "1h", (i.days as number) || 30), category: "quant" }),
    defineTool({ name: "strategy_bb_breakout", description: "Bollinger Band breakout backtest", inputSchema: inputSchema({ symbol: { type: "string", description: "Symbol" }, interval: { type: "string", description: "TF" }, period: { type: "number", description: "BB period" }, days: { type: "number", description: "Days" } }, ["symbol"]), handler: async (i) => strategyBollingerBreakout(i.symbol as string, (i.interval as string) || "1h", (i.period as number) || 20, (i.days as number) || 30), category: "quant" }),
    defineTool({ name: "strategy_compare_all", description: "Compare all strategies for a coin", inputSchema: inputSchema({ symbol: { type: "string", description: "Symbol" }, interval: { type: "string", description: "TF" }, days: { type: "number", description: "Days" } }, ["symbol"]), handler: async (i) => compareAllStrategies(i.symbol as string, (i.interval as string) || "1h", (i.days as number) || 30), category: "quant" }),
    defineTool({ name: "strategy_custom", description: "Run custom strategy from JSON config", inputSchema: inputSchema({ config: { type: "string", description: "JSON config" } }, ["config"]), handler: async (i) => { let cfg: Parameters<typeof runCustomStrategy>[0] | null = null; try { cfg = JSON.parse(i.config as string) as Parameters<typeof runCustomStrategy>[0]; } catch { return { success: false, error: "Invalid JSON" }; } if (!cfg) return { success: false, error: "Empty config" }; return runCustomStrategy(cfg); }, category: "quant" }),
  ]

});
